apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-campanha
  description: API para gerenciamento de campanhas de marketing
  owner: grupo-2
  relationships:
  - type: dependsOn
    targetRef: resource:mysql-database
  - type: dependsOn
    targetRef: resource:mongodb-database
spec:
  type: openapi
  lifecycle: experimental
  owner: equipe-api
  definition: |
    openapi: 3.0.0
    info:
      title: API de Campanha
      version: 1.0.0
      description: API que permite gerenciar campanhas de marketing, incluindo criação, atualização e listagem de campanhas.
    paths:
      /campaigns:
        get:
          summary: Lista todas as campanhas
          description: Retorna uma lista de todas as campanhas disponíveis.
          responses:
            '200':
              description: Lista de campanhas retornada com sucesso
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID da campanha
                        name:
                          type: string
                          description: Nome da campanha
        post:
          summary: Cria uma nova campanha
          description: Cria uma nova campanha com os dados fornecidos no corpo da requisição.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Nome da campanha
                    description:
                      type: string
                      description: Descrição da campanha
          responses:
            '201':
              description: Campanha criada com sucesso
            '400':
              description: Erro na criação da campanha
      /campaign:
        put:
          summary: Atualiza uma campanha existente
          description: Atualiza os dados de uma campanha existente.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID da campanha a ser atualizada
                    name:
                      type: string
                      description: Novo nome da campanha
                    description:
                      type: string
                      description: Nova descrição da campanha
          responses:
            '200':
              description: Campanha atualizada com sucesso
            '404':
              description: Campanha não encontrada

---

# Definição do MySQL como dependência
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata: 
  name: mysql-database
  description: Banco de dados MySQL usado pela API de campanhas 

spec: 
  type: database
  owner: grupo-2
  system: api-campanha
  lifecycle: dev
  parameters:
    hostname: "mysql-servidor"
    port: 3306
    database: "db_dev_campanha"
    username: "usr_dev_campanha"
    password: "QBxDsIzAfXObj46agmixK0"

---

# Definição do MongoDB como dependência
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mongodb-database
  description: Banco de dados MongoDB usado pela API de campanhas

spec:
  type: database
  owner: grupo-2
  sistem: api-campanha
  lifecycle: dev
  parameters:
    hostname: "mongo-servidor"
    port: 27017
    database: "db_dev_campanha"
    username: "usr-dev-campanha"
    password: "BR3TMiqs7P0vDRx2zqvVH3"
