apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: API-Campanha
  description: |
    Gestão de campanhas
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://localhoost/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: cogny/api-campanha
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: api
  owner: grupo2
  lifecycle: experimental