apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: default
  name: api-campanha
  description: API para gerenciamento de campanhas de marketing
  owner: grupo-2
  annotations:
    backstage.io/api-docs-url: "http://localhost:7007/api-docs" # Link do Swagger UI
spec:
  type: openapi
  lifecycle: experimental
  owner: grupo-2
  definition: |
    openapi: 3.0.0
    info:
      title: API de Campanha
      version: 1.0.0
      description: API que permite gerenciar campanhas de marketing.
    paths:
      /campaigns:
        get:
          summary: Retorna a lista de campanhas
          description: Lista todas as campanhas disponíveis.
          responses:
            '200':
              description: Lista de Campanhas sem filtragem
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Fulano de Tal'
        post:
          summary: Cria uma nova campanha
          description: Cria uma nova campanha a partir dos dados fornecidos.
          responses:
            '201':
              description: Campanha criada
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Fulano de Tal'
      /campaigns/{id}:
        put:
          summary: Atualiza uma campanha
          parameters:
            - in: path
              name: id
              required: true
              schema:
                type: string
              description: ID da campanha
          description: Atualiza os dados de uma campanha existente.
          responses:
            '200':
              description: Campanha atualizada com sucesso
